# Generated by Django 5.2.3 on 2025-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news_post",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
        migrations.AlterField(
            model_name="news_post",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название новости"),
        ),
    ]
